### ISSUE TITLE
Failed to load script: Spells.VayneTumbleUltAttack

### ISSUE THREAD

**Issue by LittleZen** [LeagueSandbox/LeagueSandbox-Default#125]
Vayne failt to load the skill ... and btw how can we start URF mode ?

**Comment by Veykril** [comment]
Without any error log this issue is quite useless. And having an URF mode is currently not a priority given that we can't even have a proper normal game at the moment either.

**Comment by danil179** [comment]
It seems that this skill is currently unimplemented, as many others champions' spells. Also, URF mode currently unimplemented, as many others modes.

This issue is also not related to this repository, as rework has been done and scripts moved to the GameServer repository.

**Comment by lzardy** [comment]
Issue can be closed as there are no Vayne skills implemented. The question is simple enough that it should have been asked in the discord.

**Comment by LittleZen** [comment]
sorry guys i didnt know about discord !
