### ISSUE TITLE
Ezreal Q has a strange second projectile which is very OP. Please, nerf it!

### ISSUE THREAD

**Issue by Deudly** [LeagueSandbox/LeagueSandbox-Default#51]

**Comment by rojnwa** [comment]
This is intended for test purposes. You can edit Ezreal's Q.cs file and following line 35 you will be able to edit that part.

**Comment by Deudly** [comment]
Man, I know it. I created the issue to create the PR after it, I was just joking. See https://github.com/LeagueSandbox/LeagueSandbox-Default/pull/52

**Comment by danil179** [comment]
Close this as it was already fixed.
