### ISSUE TITLE
Remove IPlaceable and Placeable.

### ISSUE THREAD

**Issue by yasinallahdev** [LeagueSandbox/LeagueSandbox-Default#93]
'Placeable', as an object class, are not present in League whatsoever.
Units like lane minions, jungle camps, pets, are all technically minions and are all spawned through SpawnMinion() in league (taken from BB files).
Current packet to spawn "Placeable" is incorrect and in fact a lot of the packets should be removed or replaced with LeaguePackets as they are more consistent and organized.

**Comment by danil179** [comment]
Not related here. (already in GameServer)
