### ISSUE TITLE
Reconnect problem

### ISSUE THREAD

**Issue by xxx3456789** [LeagueSandbox/LeagueSandbox-Default#96]
when Champion reconnect
you can see your spell are "disabled" and don't have spell points,
kind of big problem if we are playing in the game.

**Comment by cajthamlmatej** [comment]
Wrong repository I guess? Duplicate of https://github.com/LeagueSandbox/GameServer/issues/670 and https://github.com/LeagueSandbox/GameServer/issues/409

**Comment by danil179** [comment]
Moved this to main repo. LeagueSandbox/GameServer#805
